run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
  disable:
    - deadcode
    - structcheck
    - varcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - linters:
        - govet
      text: "possible misuse of unsafe.Pointer"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: false

  shadow: true

  staticcheck:
    checks: ["all"]

  unused:
    check-exported: true
